# Generated by Django 2.0.5 on 2018-12-20 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='卡号')),
                ('state', models.CharField(choices=[('valid', '有效'), ('invalid', '无效')], max_length=10, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('card_Email', models.EmailField(blank=True, default='', max_length=100, verbose_name='邮件')),
            ],
            options={
                'verbose_name': '門卡信息',
                'verbose_name_plural': '門卡信息',
            },
        ),
    ]
